datatrails/datatrails-python

- .github/workflows/python-package.yml
- scripts/unittests.sh
This action checks that code is properly formatted, linted and unittested
>  Github action to enforce quality

- README.md
Problem:
Use of git pull --rebase was not correct
Solution:
Use 'git merge upstream/main' to synchronize upstream
Signed-off-by: eccles phewlett76@gmail.com
> Use git merge in defined user workflow

- setup.py
Problem:
The entry points in the wheel are no longer relevant.
Solution:
Remove entry points.
> Remove entry points from wheel

- archivist/access_policies.py
- archivist/archivist.py
- archivist/assets.py
- archivist/attachments.py
- archivist/confirm.py
- archivist/errors.py
- archivist/events.py
- archivist/locations.py
- archivist/subjects.py
Problem:
Auto-complete / intellisense does not work correctly on IDE's when using this SDK
Solution:
Add type hints to all user facing classes 
Signed-off-by: Serhiy Pikho <Serhiy1@live.co.uk>
> Add type hinting to all user facing interfaces

- .gitignore
- archivist/archivist.py
- archivist/compliance.py
- archivist/constants.py
- archivist/sbommetadata.py
- archivist/sboms.py
- archivist/timestamp.py
- docs/index.rst
- docs/sboms/index.rst
- docs/sboms/sbommetadata.rst
- docs/sboms/sboms.rst
- functests/execassets.py
- functests/execattachments.py
- functests/execsboms.py
- functests/test_resources/bom.xml
- unittests/testsboms.py
Problem:
Upload and download of SBOM is missing.
Solution:
Added code to upload and download SBOMS
Signed-off-by: Paul Hewlett <phewlett75@gmail.com>
> Upload/Download SBOM

- archivist/archivist.py
- archivist/constants.py
- archivist/sbommetadata.py
- archivist/sboms.py
- functests/execsboms.py
- scripts/builder.sh
- unittests/testsboms.py
Solution:
Added publish and withdraw methods for SBOM
> Publish/Withdraw SBOM

- functests/execsboms.py
Solution:
Explicitly show progress of sboms functional test
> Tidy up sboms functional test

- Taskfile.yml
- requirements-dev.txt
Added audit target that scans code for security vulnerabilities
> Audit code for vulnerability

- archivist/access_policies.py
- archivist/appidp.py
- archivist/applications.py
- archivist/archivist.py
- archivist/assets.py
- archivist/attachments.py
- archivist/compliance.py
- archivist/compliance_policies.py
- archivist/events.py
- archivist/locations.py
- archivist/sboms.py
- archivist/subjects.py
- unittests/testaccess_policies.py
- unittests/testappidp.py
- unittests/testapplications.py
- unittests/testarchivist.py
- unittests/testassets.py
- unittests/testattachments.py
- unittests/testcompliance.py
- unittests/testcompliance_policies.py
- unittests/testevents.py
- unittests/testlocations.py
- unittests/testsboms.py
- unittests/testsubjects.py
Problem:
Debug print of class instance show unhelpful text
representation of the class.
Solution:
Added __str__ method to all classes.
Signed-off-by: Paul Hewlett <phelwtt76@gmail.com>
> Classes lack __str__ method

- docs/getting_started.rst
- docs/scan_test.rst
- examples/scan_test.py
Added example code that illustrates how to check if the daily
malware scan is occurring.
> Test if attachments are scanned for malware

- README.rst
- docs/requirements.txt
- docs/runner/events_create.rst
- examples/sbom_release.py
- requirements-dev.txt
- requirements.txt
Problem:
Some incorrect documentation.
Solution:
Fix minor faults in documentation and update sbom
release example code.
Signed-off-by: User Name <user@email.com>
> Minor fixes

- docs/runner/events_create.rst
- docs/runner/generic.rst
Problem:
Missing subject_label and incorrect asset_name
Solution:
Added subject_label and changed asset_name to asset_label
> Some minor fixes to docs

- examples/subject_create.py
Solution:
Change subjects example to use base64 encoding
> Subjects example must use imported self subject

- archivist/archivist.py
- archivist/constants.py
- archivist/tenancies.py
- docs/index.rst
- docs/tenancies.rst
- examples/access_policies_filter.py
- examples/access_policy_create.py
- examples/applications_registration.py
- examples/create_asset.py
- examples/create_event.py
- examples/filter_assets.py
- examples/filter_events.py
- examples/get_asset.py
- examples/get_publicasset.py
- examples/get_publicevent.py
- examples/runner.py
- examples/sharing_asset.py
- examples/subject_create.py
- examples/subjects_filter.py
- functests/execassets.py
- notebooks/Create Event with Verified Domain.ipynb
- unittests/testtenancies.py
Add access to the publicinfo of the tenencies endpoint.
> Tenancies: publicinfo

- archivist/tenancies.py
- examples/create_event.py
The docstrings for 2 methods are fixed.
> Some minor docs changes

- .github/workflows/python-package.yml
- Taskfile.yml
- docs/index.rst
- docs/sbom.rst
- docs/sbom.xml
- requirements-dev.txt
- scripts/sbom.sh
Problem:
IT is possible to commit changes with CVE vulnerabilities.
Solution:
Add pip audit to QA checks.
> Audit for vulnerabilities

- .github/workflows/python-package.yml
- archivist/utils.py
Changed pip audit gh action to pypa
> Pip audit gh action now pypa.

- .github/workflows/python-package.yml
- DEVELOPMENT.md
- Dockerfile-builder
- README.rst
- Taskfile.yml
- docs/features.rst
- docs/sbom.xml
> Support python 3.11

- scripts/builder.sh
- scripts/version.sh
Solution:
USe github environment variable.
> Second attempt at fixing internal version

- .github/workflows/python-publish.yml
Problem:
Internal version is incorrect.
Solution:
Use GITHUB_REF environment variable.
> Final fix for internal version

- archivist/notebooks/Create Asset and Events.ipynb
- archivist/notebooks/Find Asset and Create Attachment.ipynb
Signed-off-by: Madia Wilder <mwilder@Madias-MBP.attlocal.net>
Updated old GH repo for python sdk  for the below notebooks
Create Asset and Events
Find Asset and Create Attachment
> Updating SDK link

- archivist/notebooks/Create Compliance CURRENT OUTSTANDING Policy.ipynb
- archivist/notebooks/Create Compliance DYNAMIC TOLERANCE Policy.ipynb
- archivist/notebooks/Create Compliance PERIOD OUTSTANDING Policy.ipynb
- archivist/notebooks/Create Compliance RICHNESS Policy.ipynb
- archivist/notebooks/Create Compliance SINCE Policy.ipynb
- docs/notebooks.rst
- functests/execnotebooks.py
- pyproject.toml
- unittests/testnotebooks.py
…and adding pyproject.toml
Signed-off-by: Madia Wilder <mwilder@Madias-MBP.attlocal.net>
> Re-Adding Compliance Notebooks, Functests, Unittests, Notebooks.rst 

- requirements.txt
- scripts/build.sh
Problem:
Missing requests-toolbelt.
Solution:
Add toolbelt to requirements.txt.
> Missing dependency

- archivist/notebooks/Sharing Artist Asset with Record Labels.ipynb
Added subject id exchange verbiage as comments at the top
Added subject id exchange verbiage to create access function
> Adding subject id exchange verbiage

- .github/workflows/python-package.yml
- scripts/version.sh
Github actions tested on windows.
> Run actions on windows

- .devcontainer/Dockerfile
- .github/workflows/python-publish.yml
- .gitignore
[AB#8752](https://dev.azure.com/jitsuin/0629f48c-3979-4bbc-9026-cb06b3dfd0ae/_workitems/edit/8752)
<sub><img src="https://user-images.githubusercontent.com/4775299/87437657-e7332b00-c5ee-11ea-958d-589dfb19d72c.png" alt=" " width="10" height="9"> Mention [stepsize] in a comment if you'd like to report some technical debt. See examples [here](https://app.stepsize.com/api/demo-pr-redirect).</sub>
> Fix remaining refs to rkvst

- functests/execcompliance_policies.py
[AB#9350](https://dev.azure.com/jitsuin/0629f48c-3979-4bbc-9026-cb06b3dfd0ae/_workitems/edit/9350)
> Add extra sleep for compliancev1 functests

- functests/execcompliance_policies.py
Adjust sleeps so that tests account for time to confirmation.
Ensure that compliance policies are deleted on test exit.
Create compliance policies for each test.
Extract specific compliance_policy status from compliant_at call 
(i.e. ignore other compliance policies that may exist and incorrectly cause test failure)
[AB#9350](https://dev.azure.com/jitsuin/0629f48c-3979-4bbc-9026-cb06b3dfd0ae/_workitems/edit/9350)
> Fix compliance functests

- setup.cfg
Also test with new api token.
Testing - inspect header for this wheel in pypi for classifier python 3.9
[AB#10062](https://dev.azure.com/jitsuin/0629f48c-3979-4bbc-9026-cb06b3dfd0ae/_workitems/edit/10062)
> Fix classifier
