datatrails/datatrails-python

BUILDING.md, CODE_OF_CONDUCT.md, CONTRIBUTING.md, DCO, README.md
Add standard opensource files to repo shamelessly copied and edited from the k3s-io project.
The code-of-conduct is CNCF based.
=>  #3448 Add standard opensource files

archivist/archivist.py, archivist/attachments.py, archivist/errors.py, unittests/testerrors.py
When uploading a file the response.body is a 'MultipartEncoder' object. The parse_response function now handles this correctly if n error is encountered.
When downloading a file only the response is returned as the response.json() is consumed by the iter_content  method calls.
=>  Fix error parsing when uploading file

archivist/access_policies.py, archivist/archivist.py, archivist/assets.py, archivist/attachments.py, archivist/errors.py, archivist/events.py, archivist/locations.py, archivist/subjects.py, docs/introduction.rst
Problem:
Spelling errors ...
Solution:
Fix spelling errors and some syntax errors in docs
=> Fix minor typos

archivist/archivist.py, pylintrc
**Problem**: IDE's cannot recognise the top-level clients for Archivist, therefore IntelliSense does not work.
**Solution**: Add type hinting for the top-level clients
=> A type hinting for top level clients of Archivist 

archivist/archivist.py
Problem:
The optional type hints were accidentally deleted.
Solution:
Added type hints back and added comments in code to keep things in sync.
=> Optional type hints accidentally deleted

README.md, examples/access_policy_create.py, examples/create_asset.py, examples/create_event.py, functests/execaccess_policies.py, unittests/testaccess_policies.py, unittests/testassets.py
Problem:
Some defined behaviours have been removed from archivist.
Solution:
"Firmware", "Maintenance", "LocationUpdate" and "UserAttributes"
behaviours removed from examples and tests.
=> Remove unused behaviours

.gitignore, Taskfile.yml, archivist/access_policies.py, archivist/archivist.py, archivist/assets.py, archivist/attachments.py, archivist/events.py, archivist/locations.py, archivist/subjects.py, archivist/type_aliases.py
Problem: 
The "Basic" type checking level from Pylance notified multiple errors
Solution: 
Add the correct type hinting, and ignore type comments to deal with all Pylance errors
Signed off: Serhiy <serhiy1@live.co.uk>
=> Fix type hinting to match Pylance "basic" type checking

archivist/archivist.py, unittests/testarchivist.py
Problem: 
Currently, response objects are not accessible through the SDK, making certain actions , like checking header data, impossible to do from the user side.
Solution: 
Store the last 10 response objects in a ring buffer and provide a function in archivist to retrieve  a user selected amount
Signed off: 
Serhiy: <Serhiy1@live.co.uk>
=> Add Ring buffer to store last 10 response objects

archivist/assets.py, archivist/confirm.py, archivist/events.py
Problem: The function `wait_for_confirmation()` has an unreachable "return None" (for consumers of the function) . Pylance cannot prove that the return is unreachable due to the use of decorators and provides an erroneous type hint error. 
Solution: 
Use PEP 484 annotation to ignore the returned type and fix previous type hints.  
Signed off:
Serhiy: Serhiy1@live.co.uk
=> Fix misleading None on Error type hint  

archivist/assets.py, archivist/storage_integrity.py, docs/index.rst, docs/storage_integrity.rst, examples/create_asset.py, functests/execassets.py, unittests/testassets.py, unittests/teststorage_integrity.py
Problem:
Latest version of archivist now allows specifying whether the
asset is stored on the DLT or not.
Solution:
An enumerated StorageIntegrity type added to the assets.create()
method to allow specifying either LEDGER or TENANT_STORAGE. If
unspecified TENANT_STORAGE is used.
=> Add StorageIntegrity

unittests/testaccess_policies.py, unittests/testarchivist.py, unittests/testassets.py, unittests/testattachments.py, unittests/testevents.py, unittests/testlocations.py, unittests/testsubjects.py
Problem:
The unittests mocked session methods where they are defined instead of
where they are used.
Solution:
Use mock.patch.object() to mock self.arch._session
=> Unittests mock sessions method inplace

archivist/assets.py, archivist/events.py, examples/create_asset.py, examples/create_event.py, unittests/testassets.py, unittests/testevents.py
Problem:
The uage of wait_for_confirmation requires an extra import
and a clumsy invocation.
Solution:
Added wait_for_confimation as method in the assets and evenst classes.
=> Make wait for confirmation more ergonomic

archivist/assets.py, archivist/confirm.py, archivist/events.py, unittests/testassets.py, unittests/testevents.py
Problem:
The filter criteria for the wait_for_confirmed method can return zero
if the user has made a mistake and this will correspond to an erroneous
True result.
Solution:
Check that the no of assets/events is > 0 before entering the wait_for
loop,
=> Wait_for_confirmed returns True if assets/events do not exist

.github/workflows/python-package.yml, archivist/assets.py, examples/create_asset.py, examples/create_event.py, functests/execassets.py, unittests/testassets.py
Problem:
Assets create method allows user to chosse behaviours. This
feature is deprecated in favour of using a properties argumant.
Solution:
Remove the use of behaviours in the arg list and replace with a
properties argument. Currently only the storage integrity setting
is allowed in the properties argument. storage integrity is removed from
the arguments to assets.create. This will be consistent with other
methods across the different endpoints of the API.
=> Assets create should use Properties

README.rst, archivist/access_policies.py, archivist/archivist.py, archivist/assets.py, archivist/dictmerge.py, archivist/events.py, archivist/locations.py, archivist/subjects.py, docs/features.rst, docs/fixtures.rst, docs/index.rst, examples/create_asset.py, examples/create_event.py, functests/execassets.py, unittests/testassets.py, unittests/testfixtures.py
Problem:
Creating assets usually requires some common settings and
it is tedious to repeatedly specify them when manipulating
entities.
Solution:
Add a fixtures property that allows the user to 'accumulate'
predefined fixed settings.
=> Predefined settings for any endpoint

archivist/archivist.py, archivist/dictmerge.py, docs/fixtures.rst, functests/execassets.py, unittests/testarchivist.py, unittests/testdictmerge.py, unittests/testfixtures.py
Problem:
Using an Archivist instance before copying causes an error
when a deepcopy is attempted.
Solution:
Added __copy__() method to Archivist class
=> Deepcopy Archivist fails after use

archivist/errors.py, unittests/testerrors.py
Problem:
A 402 will be unclear in the response.
Solution:
A specific exception is raised when receiving a 402.
=> Handle 402 response code sensibly

archivist/archivist.py, archivist/confirmer.py, archivist/constants.py, archivist/errors.py, archivist/headers.py, archivist/retry429.py, unittests/testarchivist.py, unittests/testarchivistdelete.py, unittests/testarchivistget.py, unittests/testarchivistpost.py, unittests/testerrors.py
Problem:
A 429 indicates that submissions of requests is too rapid and
upstream has refused the request which should be retried later.
Solution:
If a 429 has a retry-after header then wait for the specified period
and try again up to a maximum of 3 times.
=> A 429 is retried if retry-after is specified

archivist/archivist.py, archivist/errors.py, unittests/testarchivist.py
Problem:
The cert keyword argument to Archivist() was never
implemented.
Solution:
Specifying cert will raise ArchivistNotImplemented error.
=> Raise UnimplementedError when cert option is used

archivist/access_policies.py, archivist/archivist.py, archivist/assets.py, archivist/attachments.py, archivist/compliance.py, archivist/compliance_policies.py, archivist/compliance_policy_type.py, archivist/confirmer.py, archivist/errors.py, archivist/events.py, archivist/locations.py, archivist/subjects.py, unittests/testarchivist.py, unittests/testcompliance_policy_type.py
**problem**
#69 
Type hints are out of date
**Solution**
- _wait_for_confirmation make use of overload decorators,  removing the need for #type: ignore in two places
- Archivist.count now checks that the count field in headers is present before casting the value to an int  
- Made all imports of archivist local
- Fixed some typos in comments 
**signed off**
Serhiy1@live.co.uk
=> Various type hint improvements

archivist/archivist.py
Problem: 
type hints for the different clients where deleted in the SBOM PR, breaking IDE autocomplete
Solution:
add the type hints back
signed off by: serhiy pikho <serhiy1@live.co.uk>
=> Re-introduce deleted type hints from sbom PR

archivist/access_policies.py, archivist/archivist.py, archivist/assets.py, archivist/compliance_policies.py, archivist/events.py, archivist/locations.py, archivist/sboms.py, archivist/subjects.py, unittests/testaccess_policies.py, unittests/testassets.py, unittests/testcompliance_policies.py, unittests/testevents.py, unittests/testlocations.py, unittests/testsboms.py, unittests/testsubjects.py
Problem:
The pythonSDK specified a fixed default page size instead of
defaulting to whatever uostream has defined.
Solution:
Remove DEFAULT_PAGE_SIZE constants and set default page size to
None.
=> Default page size has fixed value

archivist/subjects.py, functests/execsubjects.py
Problem:
Common practice is to be able to get subjects by
display name as well as identity.
Solution:
Archivist allows filtering on display name and this has
been enabled here (whereas before it was commented out)
=> Filter subjects on display name

.github/workflows/python-publish.yml
Problem:
The custom domain was reset on every publish.
Solution:
Add cname directive to publish workflow.
=> Custom docs domain

archivist/archivist.py, archivist/errors.py, archivist/publisher.py, archivist/sboms.py, archivist/withdrawer.py, examples/access_policies_filter.py, examples/access_policy_create.py, examples/compliance_demo.py, examples/create_asset.py, examples/create_event.py, examples/filter_assets.py, examples/filter_events.py, examples/get_asset.py, examples/subject_create.py, examples/subjects_filter.py, functests/execsboms.py, unittests/testarchivistpost.py, unittests/testsboms.py
Problem:
Common usage is now to use client credentials from an
application registration.
Solution:
Changed all example code to use client credentials.
Allow auth to be None in Archivist creation
Added functest that uses client credentials to publish SBOMS.
=> Example code still used simple authtoken

archivist/archivist.py, archivist/confirmer.py, archivist/sboms.py, archivist/uploader.py, archivist/withdrawer.py, functests/execapplications.py, functests/execsboms.py, requirements-dev.txt, scripts/unittests.sh, unittests/testarchivistpost.py, unittests/testsboms.py
Problem:
Uploading an sbom can specify the type and the privacy setting.
Solution:
Added params optional argument that specifies a dict of "sbom_type"
and "privacy".
Additionally added confim=True option to upload method to ensure that
the metadata is written to the database before return.
=> Upload SBOM with privacy and type

archivist/errors.py, archivist/sboms.py, functests/execapplications.py, functests/execsboms.py, functests/test_resources/bom.spdx, unittests/testerrors.py, unittests/testsboms.py
Problem:
SBOM upload results in a 401 code and the error handler fails
to deal wth this correctly.
Solution:
Modified the error handling to properly handle when response body
has non-JSON format.
Added extra functional tests for appidp and sboms endpoints.
=> SBOM upload client_secret failure

archivist/compliance_policy_requests.py, archivist/parser.py, archivist/sbommetadata.py, unittests/testsboms.py
Problem:
SBOMS failure because of new rkvst_link attribute
Solution:
Add rkvst_link to SBOMmetadata dataclass
=> SBOMS missing rkvst_link field

archivist/access_policies.py, archivist/applications.py, archivist/archivist.py, archivist/assets.py, archivist/attachments.py, archivist/compliance_policies.py, archivist/events.py, archivist/locations.py, archivist/sboms.py, archivist/subjects.py, functests/execattachments.py, unittests/testattachments.py
Problem:
An attachment that is not virus scanned or has a detected virus
is normally not allowed to be downloaded.
Solution:
Add optional query params to the download method in the
AssetsClient class that allows downloading bad attachment.
=> Allow downloading bad attachments

archivist/attachments.py, functests/execattachments.py, requirements.txt, unittests/testattachments.py
Problem:
Attachments: Allow_not_scanned has been replaced with 'strict' with
reversed meaning.
Solution:
Changed allow_not_scanned with strict selector.
=> Attachments selectors changed

archivist/archivist.py, archivist/confirmer.py, archivist/publisher.py, archivist/subjects.py, archivist/subjects_confirmer.py, archivist/uploader.py, archivist/utils.py, archivist/withdrawer.py, functests/execaccess_policies.py, unittests/testarchivist.py, unittests/testarchivistpost.py, unittests/testattachments.py, unittests/testrunnerassets.py, unittests/testsboms.py, unittests/testsubjects.py
Problem:
The subjects confirmation for access_policies was done in the
functional tests and was unavailable to a user. Backoff logic
was simple and not exponential.
Solution:
Added wait_for_confirmation() method to the subjects client using
a subjects confirmer similarly to confirmation logic for other
endpoints.
=> Subjects confirmation missing

README.rst, archivist/assets.py, archivist/cmds/runner/run.py, archivist/locations.py, archivist/parser.py, archivist/runner.py, archivist/utils.py, docs/runner/assets_create.rst, docs/runner/assets_create_if_not_exists.rst, docs/runner/assets_list.rst, docs/runner/compliance_compliant_at.rst, docs/runner/events_count.rst, docs/runner/events_create.rst, docs/runner/events_list.rst, docs/runner/generic.rst, functests/execassets.py, functests/execrunner.py, functests/test_resources/door_entry_story.yaml, functests/test_resources/dynamic_tolerance_story.yaml, functests/test_resources/richness_story.yaml, functests/test_resources/wipp_story.yaml, requirements-dev.txt, unittests/testassets.py, unittests/testassetsconstants.py, unittests/testlocations.py, unittests/testrunner.py, unittests/testrunnerassets.py, unittests/testrunnercompliance.py, unittests/testrunnerstep.py
Problem:
The use of an asset or location signature was considered a
inferior design. Use a selector instead where one can specify
which attributes signify a unique asset/location.
Solution:
Changed create_of_not_exists() of both assets and locations to
use a selector. Modified door_entry story.
=> Use selector instead of signature in story runner

archivist/sboms.py
Problem:
Uploading a an SBOM as an attachment may not have
a uuid field
Solution:
Do not create uuid value if it does not exist in SBOM.
=> SBOM file might not have uuid

.gitignore, setup.py
Problem:
incorrect README type and ignore secrets files
Solution:
Change content type in setup.py and added stuntidp files
to gitignore.
Signed-off-by: Paul Hewlett <phewlstt76@gmail.com>
=> Minor fixes

functests/execassets.py
Problem:
Execassets functional test still uses old syntax.
Solution:
Change to new syntax
Signed-off-by: Paul Hewlett <phelwett76@gmail.com>
=> Functional test is incorrect

DEVELOPMENT.md, archivist/parser.py, archivist/utils.py, docs/runner/execute.rst, docs/runner/index.rst, examples/access_policies_filter.py, examples/create_asset.py, examples/sbom_release.py, examples/scan_test.py, functests/execaccess_policies.py, functests/execapplications.py, functests/execassets.py, functests/execattachments.py, functests/execrunner.py, functests/execsboms.py, functests/execsubjects.py, scripts/builder.sh, scripts/functests.sh
Problem:
Currently secrets are expected to reside in a file in a
protected directory. This is not optimal in pipelines
and other environments.
Solution:
Allow specifying a secret set in an environment variable
directly.
=> Read secrets from environment

.github/workflows/python-package.yml, .github/workflows/python-publish.yml, .gitignore, DEVELOPMENT.md, Dockerfile-builder, README.rst, Taskfile.yml, docs/features.rst, docs/requirements.txt, functests/__init__.py, requirements-dev.txt, requirements.txt, setup.py, unittests/__init__.py
Problem:
Python 3.6 is EOL December 2021. Additionally we are unable
to use an increasing number of dependencies as they withdraw
support for 3.6. Subsequent work involving using swagger
json definitions to generate dataclasses is restricted to
3.7 and later.
Solution:
Remove all support for Python 3.6 and default to 3.7. Improve
the github actions to check integrity of wheel. Fix restructuted
text of README for PyPi.
=> Remove support for Python 3.6

.github/workflows/python-publish.yml
Problem:
Releaae process requires build module which
mysteriously disappeared from 3.10
Solution:
Explicitly install build package
=> Build package is missing

docs/runner/events_list.rst, docs/runner/subjects_count.rst, docs/runner/subjects_create.rst, docs/runner/subjects_create_b64.rst, docs/runner/subjects_list.rst, docs/runner/subjects_read.rst, docs/runner/subjects_update.rst, functests/test_resources/subjects_story.yaml
Problem:
Subjects YAML was incorrectly indented
Solution: 
Indent Subjects YAML correctly
Also added correct Multiline YAML syntax for b64 example - https://stackoverflow.com/questions/3790454/how-do-i-break-a-string-in-yaml-over-multiple-lines
Signed-off-by: Will Godfrey will.godfrey@rkvst.com
=> Fixing Subjects YAML Formatting

unittests/testassets.py, unittests/testassetsconstants.py, unittests/testevents.py, unittests/testsboms.py, unittests/testsubjects.py
Problem:
Sometimes the unittests involving successful upload
fail.
Solution:
For these tests the max_time parameter is too short (1s).
For expected success involving backoff increase max_time to 100s.
=> Unittests of backoff are unreliable.

archivist/runner.py, docs/runner/index.rst, docs/runner/locations_list.rst, functests/test_resources/synsation_story.values.yaml, functests/test_resources/synsation_story.yaml.j2
Problem:
Action LOCATIONS_LIST is missing from yaml runner.
Solution:
Added LOCATIONS_LIST and used the synsation functest as
demomnstration.
=> Add LOCATIONS_LIST to yaml runner

.github/workflows/python-publish.yml, Dockerfile-builder
Problem:
The docs did not publish n release because of missing
C dependency.
Solution:
Added dependency installation instructions to the github publish
workflow.
=> Docs did not publish on release

archivist/cmds/runner/run.py, examples/scan_test.py, pylintrc, requirements-dev.txt, unittests/testerrors.py, unittests/testsboms.py
Problem:
Pylint upgraded from 2.12 to 2.14 and despite the stated
adherence to semver this has caused a lot of errors from
the current values in pylintrc.
Solution:
Regenerate pylintrc and edit to fix new linting failures.
=> Upgrade to pylint causes breakage

archivist/sbommetadata.py, unittests/testsboms.py
Problem:
Tenant ID was added to the SBOM metadata and this emits
an error.
Solution:
Added tenantid to SBOM dataclass and modified unittest accordingly.
=> SBOM metadata has tenantid field

archivist/assets.py, archivist/constants.py, examples/access_policy_create.py, examples/sbom_release.py, examples/scan_test.py, functests/execaccess_policies.py, functests/execassets.py, functests/execpublicassets.py, unittests/testaccess_policies.py, unittests/testassetsconstants.py, unittests/testrunner.py, unittests/testrunnerassets.py
Problem:
BEHAVIOURS is defined in assets.py.
Solution:
Move BEHAVIOURS to constants.py as ASSET_BEHAVIOURS
=> BEHAVIOURS constant in wrong place.

archivist/access_policies.py, unittests/testaccess_policies.py
Problem:
The backend does not support counting of matching assets or
access_policies in the access_policy endpoint.
Solution:
Removed count_matching_assets() and count_matching_access_polices()
methods in access_policies endpoint.
=> Access policies count_matching methods

archivist/runner.py, archivist/subjects.py, docs/runner/components/index.rst, docs/runner/components/subjects_create.rst, docs/runner/components/subjects_delete.rst, docs/runner/components/subjects_update.rst, functests/execsubjects.py, functests/test_resources/subjects_story.yaml, unittests/testsubjects.py
Problem:
Incorrectly named as plurali.
Solution:
Change wallet_pub_keys to wallet_pub_key
Change tessera_pub_keys to tessera_pub_key
=> Misnamed arguments to subjects endpoint

archivist/assets.py, archivist/events.py, archivist/sboms.py, unittests/testsboms.py
Problem:
Assets, events and SBOMs are not confirmed by default.
Solution:
Set default value of confirm to True for assets, events and SBOMs.
Modify unittests.
=> Confirm by default

archivist/sbommetadata.py, archivist/sboms.py, unittests/testsboms.py
Problem:
Endpoints that use dataclasses will throw an uncontrolled exception when
an unexpected field is found in the response. This bug as triggered by
the new tenantid field returned by SBOM endpoint.
Solution:
Added helper function which ignores unexpected fields in SBOM
constructor.
=> Unexpected response fields.

archivist/compliance_policies.py, archivist/compliance_policy_requests.py, docs/compliance_policies_since.rst, docs/getting_started.rst, examples/compliance_policies_since.py, functests/execcompliance_policies.py, notebooks/Check Asset Compliance using SINCE Policy.ipynb, unittests/testcompliance_policy_request.py
Problem:
The Current Outstanding compliance policy is missing the
closing_event_display_type field. Additionally there are no
functional tests or example code,
Solution:
Added functional tests and corrected the current outstanding
compliance policy. Added example code and notebook.
=> Compliance policy incorrect

DEVELOPMENT.md, README.rst, archivist/compliance.py, examples/runner.py, requirements-dev.txt, requirements.txt, setup.py, typings/README.md
Problem:
Miscellaneous fixes.
Solution:
compliance_policies.compliant_at report type hint is bool
example get asset code in README.rst use old type_helper
examples/runner.py also uses type helper incorrectly
typings directory for pyright checking
later version of pyright
Add files to be changed when adding new endpoint
Bump versions in requirements*.txt
=> Miscellaneous fixes

notebooks/Check Asset Compliance using CURRENT OUTSTANDING Policy.ipynb
Signed-off-by: JAG-UK <jon.geater@gmail.com>
=> Add notebook for CURRENT OUTSTANDING compliance policies

archivist/subjects.py, archivist/utils.py, functests/execaccess_policies.py, notebooks/Share_Asset.ipynb, requirements-dev.txt, unittests/testsubjects.py
Problem:
Sharing of self subject keys is not bidirectional.
Solution:
Add subjects.share() method which efficiently shares self subjects between 2 archivist instances
=> Make sharing of subject keys easier

docs/sbom.xml, scripts/builder.sh
Problem:
The functional test do not run in pipelines where TTY is unavailble.
Solution:
Remove -it flags from docker run command.
=> Remove -it flags from docker run command

.gitignore, Taskfile.yml, pyproject.toml, requirements-dev.txt, scripts/pipeline_functests.sh
Problem:
Functional tests need to be run in the internal RKVST  CI
Solution:
Add new taskfile entry & dependencies that output the results of the functional tests in junit xml
signed-off-by: 
serhiy1@live.co.uk
=> Add new taskfile entry to run functional tests with junit XML output 

functests/execsubjects.py, scripts/pipeline_functests.sh
problem:
- The non 0 exit code from test Failures looks like script failures in the internal CD
- The test subjects count test is flakey due to other tests interfering with it
Solution:
- Set the exit code of pipeline_functests.sh to be 0
- fix the flakey test
signed-off-by:
serhiy <serhiy1@live.co.uk>
=> improve pipeline func tests task

.github/workflows/python-publish.yml, pyproject.toml
Problem:
Internal version of package is still 'dirty'
Solution:
Remove about.py so that it is regenerated on publishing.
=> Internal version is incorrect

archivist/notebooks/.gitignore, archivist/notebooks/Check Asset Compliance using CURRENT OUTSTANDING Policy.ipynb, archivist/notebooks/Check Asset Compliance using SINCE Policy.ipynb, archivist/notebooks/Create Asset and Events.ipynb, archivist/notebooks/Create Event with Verified Domain.ipynb, archivist/notebooks/Find Asset and Create Attachment.ipynb, archivist/notebooks/Find Asset and Event Creation.ipynb, archivist/notebooks/Initialization and Credentials.ipynb, archivist/notebooks/Manage_Credentials.ipynb, archivist/notebooks/Share_Asset.ipynb, archivist/parser.py, archivist/runner.py, docs/notebooks.rst, docs/notebooks/.gitignore, docs/notebooks/requirements.txt, docs/spelling_wordlist.txt, functests/execnotebooks.py, scripts/zipnotebooks.sh, unittests/testnotebooks.py
Problem:
Jupyter notebooks must be easily executable by third parties on customer's desktops.
Solution:
Add section to docs detailing how to load JupyterLab desktop on Linux, Mac or Windows. Add extra special notebook that initialises environment to the users credentials and tailor all notebooks to use the python-dotenv package to load the same environment.
=> Use jupyter notebooks on local desktop

scripts/pipeline_functests.sh
Problem:
Internal pipeline tests failed with relative import error.
Solution:
Explicitly specify the toplevel directory with -t option.
=> Internal pipeline tests failed.

scripts/pipeline_functests.sh
Solution:
Change pipeline-functest.sh to use bash
=> pipeline-functests fails

scripts/builder.sh
Problem:
'the input device is not a TTY' error when run in pipeline.
Solution:
Only use -it argument if fd 1 is a tty.
=> Builder.sh does not run in pipelines

docs/_static/css/rkvst_theme.css, pyproject.toml
Problem:
Statically defined fonts were not available at python.rkvst.com.
Solution:
Fonts were retrieved using http instead of https which failed for external users but succeeded when run locally.
=> Document fonts are incorrect

functests/execnotebooks.py
Problem:
The notebook functest for notebook 'Sharing Artist Asset with User' fails in pipeline because a root access token is required.
Solution:
Added skip clause to suppress the test.
Fixes [AB#7742](https://dev.azure.com/jitsuin/0629f48c-3979-4bbc-9026-cb06b3dfd0ae/_workitems/edit/7742)
=> Notebook test fails in pipeline

requirements-dev.txt, requirements.txt
Resolve incompatible dependencies
Problem:
Requests and requests-toolbelt had incompatible dependencies 2.30 and
0.10.1 when removing appengine support.
Solution:
Degrade requests to version 2.29.
Upgrade to latest request is deferred until all other packages
are also upgraded.
=> Resolve incompatible dependencies

.github/workflows/python-package.yml, requirements.txt
Problem:
Pip audit reports vulnerability in underlying requests package.
Solution:
Upgrade pip audit version in github action and requirements-dev.txt.
Upgrade requests and requests-toolbelt in requirements.txt.
=> Pip audit shows warning.

archivist/access_policies.py, archivist/appidp.py, archivist/applications.py, archivist/assetattachments.py, archivist/assets.py, archivist/attachments.py, archivist/cmds/runner/run.py, archivist/compliance.py, archivist/compliance_policies.py, archivist/composite.py, archivist/events.py, archivist/locations.py, archivist/runner.py, archivist/subjects.py, archivist/tenancies.py
The type-checking hints introduced circular imports. Changed the import to minimise imported symbols and only imported Archivist when type-checking was true.
Fixes [AB#8292](https://dev.azure.com/jitsuin/0629f48c-3979-4bbc-9026-cb06b3dfd0ae/_workitems/edit/8292)
=> Fix circular imports

archivist/access_policies.py, archivist/appidp.py, archivist/applications.py, archivist/archivist.py, archivist/archivistpublic.py, archivist/asset.py, archivist/assetattachments.py, archivist/assets.py, archivist/attachments.py, archivist/cmds/runner/run.py, archivist/compliance.py, archivist/compliance_policies.py, archivist/compliance_policy_requests.py, archivist/composite.py, archivist/confirmer.py, archivist/dictmerge.py, archivist/errors.py, archivist/events.py, archivist/headers.py, archivist/locations.py, archivist/or_dict.py, archivist/runner.py, archivist/sboms.py, archivist/subjects.py, archivist/subjects_confirmer.py, archivist/tenancies.py, archivist/utils.py
- Removed as the python committee decided that annotations is not the correct way to deal with cyclical imports 
- Convert necessary type hints to strings to deal with the removal of the import 
<sub><img src="https://user-images.githubusercontent.com/4775299/87437657-e7332b00-c5ee-11ea-958d-589dfb19d72c.png" alt=" " width="10" height="9"> Mention [stepsize] in a comment if you'd like to report some technical debt. See examples [here](https://app.stepsize.com/api/demo-pr-redirect).</sub>
=> Remove __fututure__ import for type hints

Dockerfile-builder
See https://github.com/nodesource/distributions#new-update-%EF%B8%8F
The nodejs installation script is no longer supported.
=> Use nodejs debian package only

.github/workflows/python-package.yml, DEVELOPMENT.md, README.rst, Taskfile.yml, docs/features.rst, docs/requirements.txt, docs/sbom.xml, requirements-dev.txt
Upgrade all dependencies that support python 3.8-3.12. Disable pyright for 3.12 as it is currently incompatible. (https://github.com/ekalinin/nodeenv/issues/341)
[AB#8633](https://dev.azure.com/jitsuin/0629f48c-3979-4bbc-9026-cb06b3dfd0ae/_workitems/edit/8633)
=> Support for python 3.12

.github/workflows/python-package.yml, .github/workflows/python-publish.yml
Replace v2 of checkout with v4 as warning received in pipeline:
'The following actions uses node12 which is deprecated and will
be forced to run on node16: actions/checkout@v2,
actions/setup-python@v2.
For more info:
https://github.blog/changelog/
2023-06-13-github-actions-all-actions-will-run-on-node16-instead
-of-node12-by-default/'
[AB#8731](https://dev.azure.com/jitsuin/0629f48c-3979-4bbc-9026-cb06b3dfd0ae/_workitems/edit/8731)
=> Upgrade checkout action.

archivist/proof_mechanism.py, docs/spelling_wordlist.txt, functests/execassets.py, unittests/testassets.py, unittests/testassetsconstants.py, unittests/testproof_mechanism.py
The ability to specify merkle log as the proof mechanism is added. Note that this requires backend support which will only be available at some future date.
[AB#9103](https://dev.azure.com/jitsuin/0629f48c-3979-4bbc-9026-cb06b3dfd0ae/_workitems/edit/9103)
=> Add merkle log proof mechanism

archivist/archivistpublic.py, functests/execassets.py, unittests/testassetsconstants.py
Both the simple_hasgh and the merkle_log tesst used the same asset signature which meant they were using the same asset for the test. Changing the signature then made the simple_hash test pass and the merkle_log fail as expected.
Fixes [AB#9157](https://dev.azure.com/jitsuin/0629f48c-3979-4bbc-9026-cb06b3dfd0ae/_workitems/edit/9157)
=> Fix simple hash functest

archivist/confirmer.py, archivist/subjects_confirmer.py, requirements.txt, unittests/testassetsconstants.py, unittests/testassetswait.py, unittests/testeventswait.py
Reduced max timeout from 1200 to 300s
Set maximum retry interval to 30s
Change wait_for_confirmed for STORED entities
[AB#9103](https://dev.azure.com/jitsuin/0629f48c-3979-4bbc-9026-cb06b3dfd0ae/_workitems/edit/9103)
=> Fix confirmation timeouts

Dockerfile-builder, archivist/proof_mechanism.py, unittests/testproof_mechanism.py
=> Restore simple hash enum

archivist/archivist.py, archivist/archivistpublic.py, functests/execaccess_policies.py, functests/execapplications.py, functests/execassets.py, functests/execattachments.py, functests/execcompliance_policies.py, functests/execnotebooks.py, functests/execpublicassets.py, functests/execrunner.py, functests/execsubjects.py, pyproject.toml, unittests/constants.py, unittests/testaccess_policies.py
User Agent is a property which can be prepended to by other packages such as datatrails-samples so that DataTrails-User-Agent is a list of agents.
datatrails-samples will have its own copy of the Archivist class that will add its own user-agent. Likewise for avid-samples-service.
Test_results:
[test_results.txt](https://github.com/user-attachments/files/16177486/test_results.txt)
Additionally the wheel was generated locally and imported into a branch for datatrails-samples. The datatrails-samples tests were run and segment output from pod logs inspected:
Segment Handler: partnerID acmecorp    {"servicename": "assetsv2"}                                                   
Segment Handler: userAgent samples/v0.17.1-2-g9d1a5d9 pysdk/v0.31.2-1-ge855a49-dirty
The 'dirty' moniker is because we …
=> Accumulate user_agent

setup.cfg
Universal wheels are deprecated:
********************************************************************************
With Python 2.7 end-of-life, support for building universal wheels
(i.e., wheels that support both Python 2 and Python 3)
is being obviated.
Please discontinue using this option, or if you still need it,
file an issue with pypa/setuptools describing your use case.
By 2025-Aug-30, you need to update your project and remove deprecated calls
or your builds will no longer be supported.
********************************************************************************
Additionally another classifier was incorrect
[AB#10062](https://dev.azure.com/jitsuin/0629f48c-3979-4bbc-9026-cb06b3dfd0ae/_workitems/edit/10062)
=> Remove deprecated universal wheel

.github/workflows/package.yml
Setup PyPi for datatrails-python to use a trusted publisher. Delete any API tokens in PyPi for datatrails-python.
In github repo delete PYPI secrets and create an environmant called release that is restricted to the main branch.
Testing: can only be tested by merging and releasing: if this fails it will be refined and remerged and rereleased. Any wheels so uploaded will be marked as alpha and yanked to prevent access by third parties.
=> Use trusted publisher and environment
